<?php

namespace Container3vGn1b7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAMQPStreamConnectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'PhpAmqpLib\Connection\AMQPStreamConnection' shared autowired service.
     *
     * @return \PhpAmqpLib\Connection\AMQPStreamConnection
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->services['PhpAmqpLib\\Connection\\AMQPStreamConnection'] = $container->createProxy('AMQPStreamConnection_99651dd', function () use ($container) {
                return \AMQPStreamConnection_99651dd::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php';

        return new \PhpAmqpLib\Connection\AMQPStreamConnection('whatever', '1234', 'floats', 'your', 'boat');
    }
}
