<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3vGn1b7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3vGn1b7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3vGn1b7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3vGn1b7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3vGn1b7\App_KernelDevDebugContainer([
    'container.build_hash' => '3vGn1b7',
    'container.build_id' => '237c1a34',
    'container.build_time' => 1607420910,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3vGn1b7');
